Repository primait/pyxis, pull requests merged in 2022-05, with the labels that each got.

#160 [DS-169]: [Pyxis SCSS] Resolve visual issues in some browsers
  packages/pyxis-elm/src/Pyxis/Components/IconSet.elm
  packages/pyxis-elm/src/Stories/Chapters/Fields/Input.elm
  packages/pyxis-icons/reload.svg
  packages/pyxis-react/src/components/Icon/Icons.tsx
  packages/pyxis-scss/package.json
  packages/pyxis-scss/postcss.config.js
  packages/pyxis-scss/src/scss/components/accordion.scss
  packages/pyxis-scss/src/scss/components/buttons.scss
  packages/pyxis-scss/src/scss/components/forms/card.scss
  packages/pyxis-scss/src/scss/components/forms/fields/text.scss
  packages/pyxis-scss/src/scss/components/forms/mixins.scss
  packages/pyxis-scss/src/scss/components/forms/toggle.scss
  packages/pyxis-scss/src/scss/components/mixins.scss
  packages/pyxis-scss/src/scss/components/modal.scss
  packages/pyxis-scss/src/scss/components/tooltip.scss
  packages/pyxis-scss/src/scss/foundations/base/form.scss
  yarn.lock
Labels: PR: Bug Fix :bug:

#168 [Pyxis Scss] - Fix cursor type on `.link` class
  packages/pyxis-scss/src/scss/components/link.scss
Labels: PR: Bug Fix :bug:

#170 [DS-191]: [Pyxis SCSS] Refactoring spacing token
  packages/pyxis-react/src/stories/Introduction.tsx
  packages/pyxis-react/src/stories/components/Badge/Badge.module.scss
  packages/pyxis-react/src/stories/components/Form/Form.module.scss
  packages/pyxis-react/src/stories/components/Icons/IconSet/IconSet.module.scss
  packages/pyxis-react/src/stories/components/Message/Message.module.scss
  packages/pyxis-react/src/stories/components/Toggle/Toggle.module.scss
  packages/pyxis-react/src/stories/components/Tooltip/Tooltip.module.scss
  packages/pyxis-react/src/stories/foundations/Spacing/Overview.tsx
  packages/pyxis-react/src/stories/foundations/Spacing/common.tsx
  packages/pyxis-react/src/stories/pyxis.scss
  packages/pyxis-react/src/stories/scss/form.scss
  packages/pyxis-react/src/stories/utils/CopyableCode/CopyableCode.module.scss
  packages/pyxis-react/src/stories/utils/OverviewTemplate/OverviewTemplate.module.scss
  packages/pyxis-react/src/stories/utils/Table/Table.module.scss
  packages/pyxis-scss/src/scss/components/accordion.scss
  packages/pyxis-scss/src/scss/components/badge.scss
  packages/pyxis-scss/src/scss/components/forms/card.scss
  packages/pyxis-scss/src/scss/components/forms/controls/control.scss
  packages/pyxis-scss/src/scss/components/forms/dropdown.scss
  packages/pyxis-scss/src/scss/components/forms/fields/field.scss
  packages/pyxis-scss/src/scss/components/forms/fields/text.scss
  packages/pyxis-scss/src/scss/components/forms/grid.scss
  packages/pyxis-scss/src/scss/components/forms/index.scss
  packages/pyxis-scss/src/scss/components/forms/item.scss
  packages/pyxis-scss/src/scss/components/forms/label.scss
  packages/pyxis-scss/src/scss/components/forms/legend.scss
  packages/pyxis-scss/src/scss/components/forms/textSwitch.scss
  packages/pyxis-scss/src/scss/components/forms/toggle.scss
  packages/pyxis-scss/src/scss/components/loaders/loader.scss
  packages/pyxis-scss/src/scss/components/message.scss
  packages/pyxis-scss/src/scss/components/mixins.scss
  packages/pyxis-scss/src/scss/components/modal.scss
  packages/pyxis-scss/src/scss/components/tooltip.scss
  packages/pyxis-scss/src/scss/foundations/spacings.scss
  packages/pyxis-scss/src/scss/tokens/breakpoints.scss
  packages/pyxis-scss/src/scss/tokens/colors.scss
  packages/pyxis-scss/src/scss/tokens/containers.scss
  packages/pyxis-scss/src/scss/tokens/elevationColors.scss
  packages/pyxis-scss/src/scss/tokens/elevationSizes.scss
  packages/pyxis-scss/src/scss/tokens/gradients.scss
  packages/pyxis-scss/src/scss/tokens/motionDuration.scss
  packages/pyxis-scss/src/scss/tokens/motionTiming.scss
  packages/pyxis-scss/src/scss/tokens/radius.scss
  packages/pyxis-scss/src/scss/tokens/spacings.scss
  packages/pyxis-scss/src/scss/tokens/textSizes.scss
  packages/pyxis-scss/src/scss/tokens/textWeights.scss
  packages/pyxis-scss/src/scss/tokens/titleSizes.scss
  packages/pyxis-scss/src/scss/tokens/titleWeights.scss
  packages/pyxis-scss/src/scss/tokens/zIndexes.scss
  packages/pyxis-tokens/json/spacings.json
Labels: PR: Breaking Change :boom:

#165 [DS-165]: [Pyxis Storybook] Documentation for Tooltip
  packages/pyxis-react/src/stories/components/Message/Overview.tsx
  packages/pyxis-react/src/stories/components/Tooltip/Overview.stories.mdx
  packages/pyxis-react/src/stories/components/Tooltip/Overview.tsx
  packages/pyxis-react/src/stories/components/Tooltip/Tooltip.module.scss
  packages/pyxis-react/src/stories/components/Tooltip/Tooltip.stories.tsx
  packages/pyxis-react/src/stories/components/Tooltip/Tooltip.tsx
  packages/pyxis-scss/src/scss/components/link.scss
Labels: PR: Docs :memo:

#172 [DS-132]: [Pyxis Elm] Refactor Dropdown
  packages/pyxis-elm/src/Examples/Form/Data.elm
  packages/pyxis-elm/src/Examples/Form/Model.elm
  packages/pyxis-elm/src/Examples/Form/Update.elm
  packages/pyxis-elm/src/Examples/Form/Views/BaseInformation.elm
  packages/pyxis-elm/src/Pyxis/Commons/Attributes.elm
  packages/pyxis-elm/src/Pyxis/Components/Field/Autocomplete.elm
  packages/pyxis-elm/src/Pyxis/Components/Field/Status.elm
  packages/pyxis-elm/src/Pyxis/Components/Form/Dropdown.elm
  packages/pyxis-elm/src/Stories/Chapters/Fields/Autocomplete.elm
  packages/pyxis-elm/tests/Components/Field/AutocompleteTest.elm
  packages/pyxis-scss/src/scss/components/forms/dropdown.scss
Labels: PR: Bug Fix :bug:, PR: New Feature :rocket:, PR: Breaking Change :boom:

#175 [DS-209]: [Pyxis Elm] Checkbox doesn't support onClick events on label
  packages/pyxis-elm/src/Examples/Form/Views/BaseInformation.elm
  packages/pyxis-elm/src/Pyxis/Components/Field/CheckboxGroup.elm
  packages/pyxis-elm/src/Stories/Chapters/Fields/CheckboxGroup.elm
  packages/pyxis-elm/tests/Components/Field/CheckboxGroupTest.elm
Labels: PR: Bug Fix :bug:

#174 [DS-196]: [Pyxis SCSS] Improve Readme
  README.md
  packages/pyxis-icons/README.md
  packages/pyxis-scss/README.md
  packages/pyxis-tokens/README.md
Labels: PR: Docs :memo:
