Repository primait/pyxis, pull requests merged in 2022-06, with the labels that each got.

#176 [DS-166]: [Pyxis Storybook] Documentation for Modal
  packages/pyxis-elm/src/Stories/Book.elm
  packages/pyxis-react/.storybook/preview.js
  packages/pyxis-react/src/stories/components/Modal/Modal.stories.tsx
  packages/pyxis-react/src/stories/components/Modal/Modal.tsx
  packages/pyxis-react/src/stories/components/Modal/Overview.stories.mdx
  packages/pyxis-react/src/stories/components/Modal/Overview.tsx
  packages/pyxis-react/src/stories/components/Toggle/Overview.tsx
  packages/pyxis-react/src/stories/components/Tooltip/Tooltip.stories.tsx
  packages/pyxis-scss/src/scss/components/link.scss
  packages/pyxis-scss/src/scss/components/modal.scss
Labels: PR: Docs :memo:

#184 [DS-202]: [Pyxis Elm] Add sublabel to toggle
  packages/pyxis-elm/src/Pyxis/Components/Toggle.elm
  packages/pyxis-elm/src/Stories/Chapters/Toggle.elm
  packages/pyxis-elm/tests/Components/ToggleTest.elm
  packages/pyxis-react/src/stories/components/Toggle/Overview.tsx
  packages/pyxis-react/src/stories/components/Toggle/Toggle.stories.tsx
  packages/pyxis-react/src/stories/components/Toggle/Toggle.tsx
Labels: PR: Breaking Change :boom:, PR: Enhancement :sparkles:

#181 [DS-201]: [Pyxis Scss][Pyxis Elm] Fix Message icon
  packages/pyxis-elm/src/Pyxis/Components/Message.elm
  packages/pyxis-elm/tests/Components/MessageTest.elm
  packages/pyxis-react/src/stories/components/Message/Message.tsx
  packages/pyxis-scss/src/scss/components/message.scss
Labels: PR: Bug Fix :bug:, PR: Enhancement :sparkles:

#179 [DS-63]: [Pyxis React] Add badge component
  packages/pyxis-react/.storybook/main.js
  packages/pyxis-react/.storybook/preview.js
  packages/pyxis-react/package.json
  packages/pyxis-react/src/components/Badge/Badge.test.tsx
  packages/pyxis-react/src/components/Badge/Badge.tsx
  packages/pyxis-react/src/components/Badge/index.ts
  packages/pyxis-react/src/stories/__image_snapshots__/storybook-test-ts-storyshots-test-badge-test-1-snap.png
  packages/pyxis-react/src/stories/components/Accordion/Accordion.stories.tsx
  packages/pyxis-react/src/stories/components/Badge/Badge.module.scss
  packages/pyxis-react/src/stories/components/Badge/Badge.stories.tsx
  packages/pyxis-react/src/stories/components/Badge/Badge.tsx
  packages/pyxis-react/src/stories/components/Badge/Overview.stories.mdx
  packages/pyxis-react/src/stories/components/Badge/Overview.tsx
  packages/pyxis-react/src/stories/components/Badge/Test.stories.tsx
  packages/pyxis-react/src/stories/components/Modal/Modal.tsx
  yarn.lock
Labels: PR: Docs :memo:, PR: New Feature :rocket:

#178 [DS-193]: [Pyxis React][Pyxis Elm] Change button default type
  packages/pyxis-elm/src/Pyxis/Components/Button.elm
  packages/pyxis-elm/tests/Components/ButtonTest.elm
  packages/pyxis-react/src/components/Button/Button.test.tsx
  packages/pyxis-react/src/components/Button/Button.tsx
  packages/pyxis-react/src/stories/components/Button/Overview.tsx
  packages/pyxis-scss/src/scss/components/buttons.scss
Labels: PR: Internal :house:, PR: Bug Fix :bug:

#187 [DS-224]: [Pyxis Scss] Fix modal close position and height on safari mobile
  packages/pyxis-scss/.stylelintrc
  packages/pyxis-scss/src/scss/components/mixins.scss
  packages/pyxis-scss/src/scss/components/modal.scss
Labels: PR: Bug Fix :bug:

#188 [DS-192]: [Pyxis Storybook] Documentation for Form.Item and Form.Input
  packages/pyxis-react/src/components/Form/Item/Item.tsx
  packages/pyxis-react/src/components/Form/Label/Label.tsx
  packages/pyxis-react/src/stories/components/Form/Form.stories.tsx
  packages/pyxis-react/src/stories/components/Form/Item/Item.stories.tsx
  packages/pyxis-react/src/stories/components/Form/Item/Overview.tsx
  packages/pyxis-react/src/stories/components/Form/ReactElement.stories.tsx
  packages/pyxis-react/src/stories/components/Input/Input.stories.tsx
  packages/pyxis-react/src/stories/components/Input/Overview.stories.mdx
  packages/pyxis-react/src/stories/components/Input/Overview.tsx
  packages/pyxis-react/src/stories/components/Label/Label.stories.tsx
  packages/pyxis-react/src/stories/components/Label/Overview.stories.mdx
  packages/pyxis-react/src/stories/components/Label/Overview.tsx
  packages/pyxis-react/src/stories/components/TextField/Overview.tsx
  packages/pyxis-react/src/stories/components/TextField/TextField.stories.tsx
  packages/pyxis-react/src/stories/components/TextField/TextField.tsx
Labels: PR: Docs :memo:

#190 [DS-216]: [Pyxis React] Add message component
  packages/pyxis-react/src/components/Icon/Icon.tsx
  packages/pyxis-react/src/components/Icon/types.ts
  packages/pyxis-react/src/components/Message/Message.test.tsx
  packages/pyxis-react/src/components/Message/Message.tsx
  packages/pyxis-react/src/components/Message/index.ts
  packages/pyxis-react/src/stories/components/Message/Message.module.scss
  packages/pyxis-react/src/stories/components/Message/Message.stories.tsx
  packages/pyxis-react/src/stories/components/Message/Message.tsx
  packages/pyxis-react/src/stories/components/Message/Overview.stories.mdx
  packages/pyxis-react/src/stories/components/Message/Overview.tsx
Labels: PR: New Feature :rocket:
